<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/model2_%ED%94%84%EB%A1%9C%ED%86%A0_%ED%83%80%EC%9E%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [111]:
game = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/raw 전체.csv', encoding='utf-8-sig')

In [ ]:
game.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/raw 전체.csv', encoding='utf-8-sig', index=False)

In [11]:
game.columns[400:]

Index(['원정선발_HR9', '원정선발_KBB', '원정구원_K9', '원정구원_BB9', '원정구원_HR9', '원정구원_KBB',
       '원정선발_kwERA', '원정구원_kwERA', '원정선발_K%', '원정구원_K%', '원정선발_BB%',
       '원정구원_BB%', '원정선발_OAVG', '원정구원_OAVG', '원정선발_OOBP', '원정구원_OOBP',
       '원정선발_OSLG', '원정구원_OSLG'],
      dtype='object')

In [36]:
game

게임키         일자 원정팀코드  ... 원정선발_OSLG  원정구원_OSLG    시즌
153   20160511KTHT0 2016-05-11    KT  ...  0.435009   0.415020  2016
154   20160511NCHH0 2016-05-11    NC  ...  0.343042   0.326409  2016
155   20160511OBSK0 2016-05-11    OB  ...  0.404100   0.365285  2016
156   20160511SSLG0 2016-05-11    SS  ...  0.421975   0.448837  2016
157   20160511WOLT0 2016-05-11    WO  ...  0.437313   0.385572  2016
...             ...        ...   ...  ...       ...        ...   ...
3195  20200719HHLG0 2020-07-19    HH  ...  0.447590   0.477419  2020
3196  20200719KTNC0 2020-07-19    KT  ...  0.400878   0.430806  2020
3197  20200719LTSS0 2020-07-19    LT  ...  0.417591   0.431442  2020
3198  20200719OBHT0 2020-07-19    OB  ...  0.419591   0.422989  2020
3199  20200719WOSK0 2020-07-19    WO  ...  0.404072   0.439378  2020

[2464 rows x 419 columns]

In [112]:
game['일자'] = pd.to_datetime(game['일자'],format='%Y%m%d', errors='raise')

In [113]:
game['시즌'] = game['일자'].dt.year

In [114]:
team_list = []
for year in range(2016, 2021):
  a = game[(game['일자'] > '{}-05-10'.format(year)) & (game['시즌'] == year)]
  team_list.append(a)
game = pd.concat(team_list)

In [115]:
columns = ['홈평균자책점', '홈RA/9',
       '홈ERC', '홈FIP', '홈kwERA', '홈LOB', '홈HR%', '홈K%', '홈BB%', '홈K9', '홈BB9',
       '홈HR9', '홈KBB', '홈whip', '홈P/G', '홈P/IP', '홈P/PA', '홈PFR', '홈CYP',
       '홈F-E', '홈R-E', '홈OAVG', '홈OOBP', '홈OSLG', '홈OOPS', '원정평균자책점', '원정RA/9',
       '원정ERC', '원정FIP', '원정kwERA', '원정LOB', '원정HR%', '원정K%', '원정BB%', '원정K9',
       '원정BB9', '원정HR9', '원정KBB', '원정whip', '원정P/G', '원정P/IP', '원정P/PA',
       '원정PFR', '원정CYP', '원정F-E', '원정R-E', '원정OAVG', '원정OOBP', '원정OSLG',
       '원정OOPS', '홈OBP', '홈SLG', '홈OPS', '홈GPA', '홈타율', '홈BABIP', '홈ISO',
       '홈HR%.1', '홈K%.1', '홈BB%.1', '홈BBK', '홈wOBA', '홈wRAA', '홈wRC', '홈RC',
       '홈RC27', '홈XR', '홈SPD', '홈SECA', '홈PSN', '원정OBP', '원정SLG', '원정OPS',
       '원정GPA', '원정타율', '원정BABIP', '원정ISO', '원정HR%.1', '원정K%.1', '원정BB%.1',
       '원정BBK', '원정wOBA', '원정wRAA', '원정wRC', '원정RC', '원정RC27', '원정XR', '원정SPD',
       '원정SECA', '원정PSN', '결과', '홈상대OBP', '홈상대SLG', '홈상대OPS', '홈상대GPA', '홈상대타율', '홈상대BABIP', '홈상대ISO', '홈상대HR%', '홈상대K%',
       '홈상대BB%', '홈상대BBK', '홈상대wOBA', '홈상대wRAA', '홈상대wRC', '홈상대RC', '홈상대RC27',
       '홈상대XR', '홈상대SPD', '홈상대SECA', '홈상대PSN', '원정상대OBP', '원정상대SLG', '원정상대OPS',
       '원정상대GPA', '원정상대타율', '원정상대BABIP', '원정상대ISO', '원정상대HR%', '원정상대K%',
       '원정상대BB%', '원정상대BBK', '원정상대wOBA', '원정상대wRAA', '원정상대wRC', '원정상대RC',
       '원정상대RC27', '원정상대XR', '원정상대SPD', '원정상대SECA', '원정상대PSN', '홈상대평균자책점',
       '홈상대RA/9', '홈상대ERC', '홈상대FIP', '홈상대kwERA', '홈상대LOB', '홈상대HR%.1',
       '홈상대K%.1', '홈상대BB%.1', '홈상대K9', '홈상대BB9', '홈상대HR9', '홈상대KBB', '홈상대whip',
       '홈상대PFR', '홈상대P/G', '홈상대P/IP', '홈상대P/PA', '홈상대CYP', '홈상대F-E', '홈상대R-E',
       '홈상대OAVG', '홈상대OOBP', '홈상대OSLG', '홈상대OOPS', '원정상대평균자책점', '원정상대RA/9',
       '원정상대ERC', '원정상대FIP', '원정상대kwERA', '원정상대LOB', '원정상대HR%.1', '원정상대K%.1',
       '원정상대BB%.1', '원정상대K9', '원정상대BB9', '원정상대HR9', '원정상대KBB', '원정상대whip',
       '원정상대PFR', '원정상대P/G', '원정상대P/IP', '원정상대P/PA', '원정상대CYP', '원정상대F-E',
       '원정상대R-E', '원정상대OAVG', '원정상대OOBP', '원정상대OSLG', '원정상대OOPS', '홈최근평균자책점',
       '홈최근RA/9', '홈최근ERC', '홈최근FIP', '홈최근kwERA', '홈최근LOB', '홈최근HR%', '홈최근K%',
       '홈최근BB%', '홈최근K9', '홈최근BB9', '홈최근HR9', '홈최근KBB', '홈최근whip', '홈최근PFR', '홈최근P/G', '홈최근P/IP', '홈최근P/PA', '홈최근CYP',
       '홈최근F-E', '홈최근R-E', '홈최근OAVG', '홈최근OOBP', '홈최근OSLG', '홈최근OOPS',
       '원정최근평균자책점', '원정최근RA/9', '원정최근ERC', '원정최근FIP', '원정최근kwERA', '원정최근LOB',
       '원정최근HR%', '원정최근K%', '원정최근BB%', '원정최근K9', '원정최근BB9', '원정최근HR9',
       '원정최근KBB', '원정최근whip', '원정최근PFR', '원정최근P/G', '원정최근P/IP', '원정최근P/PA',
       '원정최근CYP', '원정최근F-E', '원정최근R-E', '원정최근OAVG', '원정최근OOBP', '원정최근OSLG',
       '원정최근OOPS', '홈최근OBP', '홈최근SLG', '홈최근OPS', '홈최근GPA', '홈최근타율', '홈최근BABIP',
       '홈최근ISO', '홈최근HR%.1', '홈최근K%.1', '홈최근BB%.1', '홈최근BBK', '홈최근wOBA',
       '홈최근wRAA', '홈최근wRC', '홈최근RC', '홈최근RC27', '홈최근XR', '홈최근SPD', '홈최근SECA',
       '홈최근PSN', '원정최근OBP', '원정최근SLG', '원정최근OPS', '원정최근GPA', '원정최근타율',
       '원정최근BABIP', '원정최근ISO', '원정최근HR%.1', '원정최근K%.1', '원정최근BB%.1', '원정최근BBK',
       '원정최근wOBA', '원정최근wRAA', '원정최근wRC', '원정최근RC', '원정최근RC27', '원정최근XR',
       '원정최근SPD', '원정최근SECA', '원정최근PSN', '홈NC', '홈OB', '홈WO', '홈HT', '홈LG',
       '홈SS', '홈KT', '홈LT', '홈SK', '홈HH', '홈우취', '홈연장', 
        '홈평균득점', '홈평균실점', '홈승률', '홈피타고리안기대승률', '홈상대총득점', '홈상대총실점', '홈상대평균득점', '홈상대평균실점', '홈상대승률', '홈상대피타고리안기대승률',
       '홈최근총득점', '홈최근총실점', '홈최근평균득점', '홈최근평균실점', '홈최근승률', '홈최근피타고리안기대승률',
       '홈총합연봉', '홈평균연봉', '원정NC', '원정OB', '원정WO', '원정HT', '원정LG', '원정SS',
       '원정KT', '원정LT', '원정SK', '원정HH', '원정우취', '원정연장','원정총득점',
       '원정총실점', '원정평균득점', '원정평균실점', '원정승수', '원정패배수', '원정승률', '원정피타고리안기대승률',
       '원정상대총득점', '원정상대총실점', '원정상대평균득점', '원정상대평균실점', '원정상대승률', '원정상대피타고리안기대승률',
       '원정최근총득점', '원정최근총실점', '원정최근평균득점', '원정최근평균실점', '원정최근승률', '원정최근피타고리안기대승률',
       '원정총합연봉', '원정평균연봉',
       '홈선발_평균자책점', '홈구원_평균자책점', '홈선발_RA/9', '홈구원_RA/9',
       '홈선발_ERC', '홈구원_ERC', '홈선발_FIP', '홈구원_FIP', '홈선발_LOB', '홈구원_LOB',
       '홈선발_홈런율', '홈선발_삼진율', '홈구원_홈런율', '홈구원_삼진율', '홈선발_K9', '홈선발_BB9',
       '홈선발_HR9', '홈선발_KBB', '홈구원_K9', '홈구원_BB9', '홈구원_HR9', '홈구원_KBB',
       '홈선발_kwERA', '홈구원_kwERA', '홈선발_K%', '홈구원_K%', '홈선발_BB%', '홈구원_BB%',
       '홈선발_OAVG', '홈구원_OAVG', '홈선발_OOBP', '홈구원_OOBP', '홈선발_OSLG', '홈구원_OSLG',
       '원정선발_평균자책점', '원정구원_평균자책점', '원정선발_RA/9', '원정구원_RA/9', '원정선발_ERC',
       '원정구원_ERC', '원정선발_FIP', '원정구원_FIP', '원정선발_LOB', '원정구원_LOB', '원정선발_홈런율',
       '원정선발_삼진율', '원정구원_홈런율', '원정구원_삼진율', '원정선발_K9', '원정선발_BB9', '원정선발_HR9', '원정선발_KBB', '원정구원_K9', '원정구원_BB9', '원정구원_HR9', '원정구원_KBB',
       '원정선발_kwERA', '원정구원_kwERA', '원정선발_K%', '원정구원_K%', '원정선발_BB%',
       '원정구원_BB%', '원정선발_OAVG', '원정구원_OAVG', '원정선발_OOBP', '원정구원_OOBP',
       '원정선발_OSLG', '원정구원_OSLG']

In [116]:
game = game[columns]

In [117]:
y= game['결과'].copy()
del game['결과']

In [118]:
x= game.copy()

In [119]:
x1 = x.values
y1 = y.values

In [120]:
x1.shape
y1.shape

(2464,)

In [121]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x1, y1, test_size = 0.3 ,shuffle=False
)

In [122]:
x_train.shape

(1724, 402)

In [123]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
print(standardScaler.fit(x_train))
x_train = standardScaler.transform(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)


In [ ]:
x_train

array([[-1.11818569, -0.77612363, -0.10592686, ..., -0.44892221,
         0.01704097,  0.49760886],
       [ 2.73065108,  3.31010643,  3.0758458 , ...,  0.58246352,
         1.84630645, -0.15506923],
       [-1.50323825, -1.51334632, -1.45232633, ..., -1.85431796,
        -0.17219339, -0.90113696],
       ...,
       [-0.12853306, -0.24526028,  0.12822957, ...,  2.14546611,
         0.12742768,  1.39477891],
       [-2.18721319, -2.25687006, -1.94646527, ..., -2.15238271,
        -1.74914639, -1.3093231 ],
       [-1.0253002 , -1.23452492, -1.92236093, ..., -0.24803473,
        -0.96066989, -0.57479791]])

In [124]:
standardScaler = StandardScaler()
print(standardScaler.fit(x_test))
x_test = standardScaler.transform(x_test)

StandardScaler(copy=True, with_mean=True, with_std=True)


In [ ]:
x_test

array([[-0.61593711, -0.51325392, -0.55744495, ...,  1.64159241,
        -0.00614575, -0.6779306 ],
       [-2.03643257, -1.87076346, -1.59489516, ...,  0.22140685,
         0.23321517,  0.89554161],
       [ 0.47803975,  0.31030187,  0.96821714, ...,  1.908022  ,
         0.64810743,  1.42459487],
       ...,
       [-0.03266883,  0.04914289,  0.23441089, ..., -0.27901742,
         0.24917256,  0.63131254],
       [-0.26709244, -0.28312373, -0.54553734, ...,  1.30334266,
        -0.10189012,  0.15522412],
       [ 0.54501793,  0.58568238,  0.69731909, ...,  0.24843594,
         2.00448597,  2.93736581]])

In [125]:
from keras.models import Sequential
from keras.layers import Dense
from keras import metrics
model = Sequential()
model.add(Dense(128, input_shape=(402, )))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation= 'sigmoid'))

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=[metrics.binary_accuracy])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model.fit(x_train, y_train, validation_split=0.2, verbose = 1,
          batch_size=1, epochs=100, callbacks = [early_stopping])

loss, accuracy = model.evaluate(x_test, y_test, batch_size=1)
print('lose: ', loss)
print('mse: ', accuracy)

y_pred = model.predict(x_test)

Epoch 1/100
1379/1379 [==============================] - 3s 2ms/step - loss: 0.7385 - binary_accuracy: 0.5083 - val_loss: 0.7266 - val_binary_accuracy: 0.5478
Epoch 2/100
1379/1379 [==============================] - 3s 2ms/step - loss: 0.7044 - binary_accuracy: 0.5453 - val_loss: 0.7532 - val_binary_accuracy: 0.5159
Epoch 3/100
1379/1379 [==============================] - 3s 2ms/step - loss: 0.6927 - binary_accuracy: 0.5547 - val_loss: 0.6960 - val_binary_accuracy: 0.4522
Epoch 4/100
1379/1379 [==============================] - 3s 2ms/step - loss: 0.6870 - binary_accuracy: 0.5649 - val_loss: 0.6999 - val_binary_accuracy: 0.4899
Epoch 5/100
1379/1379 [==============================] - 3s 2ms/step - loss: 0.6776 - binary_accuracy: 0.5787 - val_loss: 0.6999 - val_binary_accuracy: 0.4957
Epoch 6/100
1379/1379 [==============================] - 3s 2ms/step - loss: 0.6754 - binary_accuracy: 0.5961 - val_loss: 0.7452 - val_binary_accuracy: 0.5217
Epoch 7/100
1379/1379 [=======================

In [127]:
for idx, i in enumerate(y_pred):
  if i >= 0.5:
    y_pred[idx] = 1
  else:
    y_pred[idx] = 0

In [132]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc
confusion_matrix = confusion_matrix(y_test,y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test,y_pred)
print(confusion_matrix)
print('recall:' + str(recall) +", precision: " + str(precision) + 'F1-score: ' + str(f1))
roc_auc = roc_auc_score(y_test,y_pred)
roc_auc

[[144 188]
 [165 243]]
recall:0.5955882352941176, precision: 0.5638051044083526F1-score: 0.5792610250297974


0.5146615875265769

In [134]:
import plotly.express as px

fpr, tpr, thresholds = roc_curve(y_test, y_pred)
fig = px.area(
    x=fpr, y=tpr,
    title=f'ROC Curve (AUC={auc(fpr, tpr):.4f})',
    labels=dict(x='False Positive Rate', y='True Positive Rate'),
    width=700, height=500
)
fig.add_shape(
    type='line', line=dict(dash='dash'),
    x0=0, x1=1, y0=0, y1=1
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_xaxes(constrain='domain')
fig.show()

In [135]:
# 회귀 평가 RMSE, R2, RMSLE
from sklearn.metrics import mean_squared_error, r2_score, mean_squared_log_error
import numpy as np
def RMSE(y_test, y_pred):
  return np.sqrt(mean_squared_error(y_test, y_pred))
def RMSLE(y_test, y_pred):
  return np.sqrt(mean_squared_log_error(y_test, y_pred))
rsme = RMSE(y_test, y_pred)
rsmle = RMSLE(y_test, y_pred)
r2 = r2_score(y_test, y_pred)