<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/Model5_%EB%93%9D%EC%A0%90_%EC%8B%A4%EC%A0%90_basic_%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [97]:
data = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/팀별 raw 데이터.csv', encoding='utf-8-sig')

In [98]:
data['일자'] = pd.to_datetime(data['일자'], format='%Y-%m-%d', errors='raise')
data['시즌'] = data['일자'].dt.year

In [99]:
team_list = []
for year in range(2016, 2021):
  a = data[(data['일자'] > '{}-05-10'.format(year)) & (data['시즌'] == year)]
  team_list.append(a)
data = pd.concat(team_list)

In [100]:
data = data[data['결과'] != 'D']
data = data[(data['우취'] != 1 ) & (data['연장'] != 1)]
out_list = ['20160810LTNC0', '20170712NCHT0', '20170725SKHT0', '20190529SSOB0', '20200512KTNC0', '20200521SKWO0', '20200703LGSS0']
for i in out_list:
  data = data[data['게임키'] != i]

In [188]:
data = data[data['득점'] <=10]

In [194]:
data

게임키         일자 팀코드  ...   구원_OOBP   선발_OSLG   구원_OSLG
306   20160511KTHT0 2016-05-11  HT  ...  0.373626  0.413844  0.382637
307   20160511KTHT0 2016-05-11  KT  ...  0.349398  0.435009  0.415020
308   20160511NCHH0 2016-05-11  HH  ...  0.387054  0.495025  0.452160
309   20160511NCHH0 2016-05-11  NC  ...  0.307292  0.343042  0.326409
310   20160511OBSK0 2016-05-11  SK  ...  0.346241  0.391185  0.401055
...             ...        ...  ..  ...       ...       ...       ...
6395  20200719LTSS0 2020-07-19  LT  ...  0.346351  0.417591  0.431442
6396  20200719OBHT0 2020-07-19  HT  ...  0.348754  0.387865  0.415655
6397  20200719OBHT0 2020-07-19  OB  ...  0.360324  0.419591  0.422989
6398  20200719WOSK0 2020-07-19  SK  ...  0.375378  0.378891  0.454439
6399  20200719WOSK0 2020-07-19  WO  ...  0.338318  0.404072  0.439378

[4101 rows x 220 columns]

In [48]:
x_data = data[[
        'SLG', 'OPS', '타율',
       'BABIP', 'ISO', 'HR%_x', 'K%_x',  'BBK', 'wOBA',  'wRC',
       'RC', 'RC27', 'XR', 'SPD', 'SECA','RBI_PCT', 
       'RA/9', 'ERC', 'FIP','LOB', 'HR%_y', 'K9',
       'BB9', 'KBB', 'whip', 'P/G', 'P/IP', 'P/PA', 'PFR', 'CYP', 
      'OOPS',  '상대RA/9', '상대ERC',
       '상대kwERA', '상대LOB', '상대HR%_x',  '상대BB9', '상대HR9', 
       '상대whip','상대P/G', '상대P/IP','상대P/PA', '상대CYP', 
        '상대OAVG', '상대OSLG', '상대HR%_y', 
       '상대BB%_y', '상대wOBA', '상대wRAA', '상대wRC', '상대RC27',
       '상대SPD',  '상대PSN', '최근OBP',  '최근GPA',
       '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK',
       '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근SPD',
       '최근PSN', '최근평균자책점',  '최근FIP', 
       '최근LOB', '최근HR%_y', '최근K%_y', '최근BB%_y', '최근HR9',
      '최근P/G', '최근P/IP','최근CYP',
      '최근R-E',  '선발_평균자책점',
        '선발_whip',
      '선발_FIP',  '선발_LOB', '선발_홈런율', '선발_삼진율',
       '선발_K%', 
       '선발_OAVG',  '선발_OOBP']]
y_data = data[['득점']]


In [215]:
# 'SLG', 'OPS', '타율',
#        'BABIP', 'ISO', 'HR%_x', 'K%_x',  'BBK', 'wOBA',  'wRC',
#        'RC', 'RC27', 'XR', 'SPD', 'SECA','RBI_PCT',
# '상대HR%_y', 
#        '상대BB%_y', '상대wOBA', '상대wRAA', '상대wRC', '상대RC27',
#        '상대SPD',  '상대PSN', '최근OBP',  '최근GPA',
#        '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK',
#        '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근SPD',
#        '최근PSN' 

x_data_h = data[[
'상대HR%_y', 
       '상대BB%_y', '상대wOBA', '상대wRAA', '상대wRC', '상대RC27',
       '상대SPD',  '상대PSN', '최근OBP',  '최근GPA',
       '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK',
       '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근SPD',
       '최근PSN' ]]
x_data_p = data[['RA/9', 'ERC', 'FIP','LOB', 'HR%_y', 'K9',
       'BB9', 'KBB', 'whip', 'P/G', 'P/IP', 'P/PA', 'PFR', 'CYP', 
      'OOPS',  '상대RA/9', '상대ERC',
       '상대kwERA', '상대LOB', '상대HR%_x',  '상대BB9', '상대HR9', 
       '상대whip','상대P/G', '상대P/IP','상대P/PA', '상대CYP', 
        '상대OAVG', '상대OSLG', '최근평균자책점',  '최근FIP', 
       '최근LOB', '최근HR%_y', '최근K%_y', '최근BB%_y', '최근HR9',
      '최근P/G', '최근P/IP','최근CYP',
      '최근R-E','선발_평균자책점',
        '선발_whip',
      '선발_FIP',  '선발_LOB', '선발_홈런율', '선발_삼진율',
       '선발_K%', 
       '선발_OAVG',  '선발_OOBP']]

y_data_h = data[['득점']]
y_data_p = data[['실점']]

In [196]:
x_data_h.shape

(4101, 20)

In [216]:
x_data_h = x_data_h.values
x_data_p = x_data_p.values
y_data_h = y_data_h.values
y_data_p = y_data_p.values

In [217]:
y_data_h

array([[8],
       [3],
       [6],
       ...,
       [8],
       [4],
       [3]])

In [218]:
from sklearn.model_selection import train_test_split
x_train_h, x_test_h, y_train_h, y_test_h = train_test_split(
    x_data_h, y_data_h, test_size = 0.3 ,shuffle=False
)
from sklearn.model_selection import train_test_split
x_train_p, x_test_p, y_train_p, y_test_p = train_test_split(
    x_data_p, y_data_p, test_size = 0.3 ,shuffle=False
)

In [219]:
y_test_h

array([[6],
       [9],
       [2],
       ...,
       [8],
       [4],
       [3]])

In [220]:
from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_train_h))
x_train_h = robustScaler.transform(x_train_h)

from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_test_h))
x_test_h = robustScaler.transform(x_test_h)

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)
RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)


In [222]:
#득점
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics

model_h = Sequential()
model_h.add(Dense(64, input_shape=(24, ), kernel_initializer='he_normal', activation='relu'))
model_h.add(Dropout(0.5))  
model_h.add(Dense(32, kernel_initializer='he_normal',activation = 'relu'))
model_h.add(Dropout(0.5))  
model_h.add(Dense(8, kernel_initializer='he_normal',activation = 'relu'))
model_h.add(Dropout(0.5))  
model_h.add(Dense(1))

model_h.compile(loss='mse', optimizer = 'adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model_h.fit(x_train_h, y_train_h, validation_split=0.2, verbose = 1,
          batch_size=1, epochs=100, callbacks = [early_stopping])

loss, accuracy = model_h.evaluate(x_test_h, y_test_h, batch_size=1)
print('lose: ', loss)
print('mse: ', accuracy)

y_pred = model_h.predict(x_test_h)

Epoch 1/100
2296/2296 [==============================] - 3s 1ms/step - loss: 16.6613 - mse: 16.6613 - val_loss: 11.3840 - val_mse: 11.3840
Epoch 2/100
2296/2296 [==============================] - 3s 1ms/step - loss: 12.0321 - mse: 12.0321 - val_loss: 9.5521 - val_mse: 9.5521
Epoch 3/100
2296/2296 [==============================] - 3s 1ms/step - loss: 9.5608 - mse: 9.5608 - val_loss: 8.2994 - val_mse: 8.2994
Epoch 4/100
2296/2296 [==============================] - 3s 1ms/step - loss: 8.3623 - mse: 8.3623 - val_loss: 7.9413 - val_mse: 7.9413
Epoch 5/100
2296/2296 [==============================] - 3s 1ms/step - loss: 8.0098 - mse: 8.0098 - val_loss: 7.7289 - val_mse: 7.7289
Epoch 6/100
2296/2296 [==============================] - 3s 1ms/step - loss: 7.7512 - mse: 7.7512 - val_loss: 7.7160 - val_mse: 7.7160
Epoch 7/100
2296/2296 [==============================] - 3s 1ms/step - loss: 7.6212 - mse: 7.6212 - val_loss: 7.7512 - val_mse: 7.7512
Epoch 8/100
2296/2296 [==========================

In [190]:
x_test_h

array([[ 0.46551724,  0.04      ,  0.20701169, ..., -0.38076336,
        -0.36046512, -1.22460351],
       [ 0.39655172,  0.49      ,  0.47412354, ..., -0.38564885,
         0.05813953, -1.22460351],
       [-0.32758621, -0.64      , -0.5542571 , ..., -1.10687023,
        -0.48837209, -0.58165452],
       ...,
       [ 0.65517241,  0.47      ,  0.56093489, ...,  1.06412214,
        -0.04651163,  0.147021  ],
       [ 0.03448276, -0.16      , -0.10016694, ...,  0.76305344,
        -0.08139535,  1.2756108 ],
       [ 0.65517241,  0.61      ,  0.66110184, ...,  0.22992366,
         1.48837209,  2.1508787 ]])

In [223]:
for i in range(len(y_pred)):
  print(y_pred[i], y_test_h[i])

[4.538769] [6]
[4.6463027] [9]
[4.7307425] [2]
[4.537785] [4]
[4.529346] [3]
[4.5444703] [4]
[4.769351] [5]
[4.5542502] [2]
[4.5542502] [6]
[4.6940365] [3]
[4.5408854] [4]
[4.6317387] [8]
[4.6934705] [7]
[4.5154395] [6]
[4.5368237] [0]
[4.7451406] [3]
[4.536144] [6]
[4.5542502] [2]
[4.5496497] [2]
[4.6810455] [1]
[4.491793] [3]
[4.693343] [2]
[4.635219] [2]
[4.580444] [1]
[4.693343] [7]
[4.500645] [1]
[4.5304775] [5]
[4.693343] [4]
[4.4828296] [2]
[4.702527] [3]
[4.6657634] [6]
[4.626821] [2]
[4.555099] [8]
[4.5542502] [0]
[4.693343] [4]
[4.506902] [5]
[4.5542502] [4]
[4.5542502] [3]
[4.695395] [2]
[4.5500474] [0]
[4.621722] [0]
[4.5516634] [9]
[4.693343] [0]
[4.546645] [4]
[4.518734] [4]
[4.5542502] [1]
[4.54469] [1]
[4.685693] [7]
[4.69519] [1]
[4.5338783] [6]
[4.5502386] [9]
[4.5309377] [3]
[4.693343] [6]
[4.7029634] [7]
[4.697759] [3]
[4.583754] [2]
[4.5498233] [7]
[4.51633] [5]
[4.693343] [1]
[4.6211205] [3]
[4.5542502] [2]
[4.682869] [3]
[4.695473] [1]
[4.6785207] [8]
[4.6905947]

In [137]:
x_test_h[0:3,]

array([[ 3.56000000e-01,  6.85000000e-01,  2.58000000e-01,
         3.06000000e-01,  9.80000000e-02,  1.40000000e-02,
         1.77000000e-01,  4.72000000e-01,  3.21000000e-01,
         2.25887000e+02,  2.17937000e+02,  3.93900000e+00,
         2.22050000e+02,  4.24000000e+00,  2.00000000e-01,
         9.89583330e-02,  9.00000000e-03,  7.00000000e-02,
         2.83000000e-01, -9.12800000e+00,  1.63050000e+01,
         3.08200000e+00,  4.05400000e+00,  2.00000000e+00,
         3.65000000e-01,  2.63000000e-01,  2.79000000e-01,
         3.12000000e-01,  1.16000000e-01,  1.31000000e-01,
         9.00000000e-02,  7.31000000e-01,  3.55000000e-01,
         3.21800000e+00,  2.67670000e+01,  2.42840000e+01,
         4.85700000e+00,  2.40920000e+01,  3.41300000e+00,
         0.00000000e+00],
       [ 4.48000000e-01,  8.04000000e-01,  2.93000000e-01,
         3.31000000e-01,  1.55000000e-01,  2.70000000e-02,
         1.68000000e-01,  4.51000000e-01,  3.67000000e-01,
         3.15971000e+02,  2.97

In [135]:
model_h.predict(x_test_h[0:10,])

array([[5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548]], dtype=float32)

In [204]:
from sklearn.metrics import mean_squared_error, r2_score, mean_squared_log_error
import numpy as np
def RMSE(y_test, y_pred):
  return np.sqrt(mean_squared_error(y_test, y_pred))
def RMSLE(y_test, y_pred):
  return np.sqrt(mean_squared_log_error(y_test, y_pred))
rsme = RMSE(y_test_h, y_pred)
rsmle = RMSLE(y_test_h, y_pred)
r2 = r2_score(y_test_h, y_pred)

In [167]:
from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_train_p))
x_train_p = robustScaler.transform(x_train_p)

from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_test_p))
x_test_p = robustScaler.transform(x_test_p)

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)
RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)


In [205]:
print(rsme)
print(rsmle)
print(r2)

2.7724895015544524
0.6978459223837162
-0.03963146512942495


In [168]:
#실점
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics

model_p = Sequential()
model_p.add(Dense(64, input_shape=(49, ), kernel_initializer='he_normal', activation='relu'))
model_p.add(Dropout(0.5))  
model_p.add(Dense(64, kernel_initializer='he_normal',activation = 'relu'))
model_p.add(Dropout(0.5))  
model_p.add(Dense(32, kernel_initializer='he_normal',activation = 'relu'))
model_p.add(Dropout(0.5))  
model_p.add(Dense(1))

model_p.compile(loss='mse', optimizer = 'adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model_p.fit(x_train_p, y_train_p, validation_split=0.2, verbose = 1,
          batch_size=1, epochs=100, callbacks = [early_stopping])

loss, accuracy = model_p.evaluate(x_test_p, y_test_p, batch_size=1)
print('lose: ', loss)
print('mse: ', accuracy)

y_pred = model_p.predict(x_test_p)

Epoch 1/100
2534/2534 [==============================] - 4s 1ms/step - loss: 23.3892 - mse: 23.3892 - val_loss: 21.8399 - val_mse: 21.8399
Epoch 2/100
2534/2534 [==============================] - 3s 1ms/step - loss: 18.1499 - mse: 18.1499 - val_loss: 18.1675 - val_mse: 18.1675
Epoch 3/100
2534/2534 [==============================] - 3s 1ms/step - loss: 16.9568 - mse: 16.9568 - val_loss: 17.8426 - val_mse: 17.8426
Epoch 4/100
2534/2534 [==============================] - 3s 1ms/step - loss: 15.9262 - mse: 15.9262 - val_loss: 16.9812 - val_mse: 16.9812
Epoch 5/100
2534/2534 [==============================] - 3s 1ms/step - loss: 15.5375 - mse: 15.5375 - val_loss: 16.3708 - val_mse: 16.3708
Epoch 6/100
2534/2534 [==============================] - 3s 1ms/step - loss: 14.9062 - mse: 14.9062 - val_loss: 15.8561 - val_mse: 15.8561
Epoch 7/100
2534/2534 [==============================] - 3s 1ms/step - loss: 14.7455 - mse: 14.7455 - val_loss: 14.9577 - val_mse: 14.9577
Epoch 8/100
2534/2534 [====

In [169]:
for i in range(len(y_pred)):
  print(y_pred[i], y_test_h[i])

[5.1632667] [3]
[5.0301685] [2]
[5.4435763] [3]
[5.048087] [2]
[5.4715705] [6]
[5.115162] [1]
[5.582367] [3]
[5.2090945] [2]
[5.102939] [0]
[5.3908873] [6]
[5.184081] [5]
[5.0652905] [1]
[5.662124] [13]
[5.084039] [3]
[5.5043716] [5]
[5.1710835] [2]
[5.5433774] [0]
[5.2778215] [4]
[5.0962296] [5]
[5.428798] [2]
[5.218754] [1]
[5.1729445] [4]
[5.7428827] [4]
[5.032821] [7]
[5.4902334] [3]
[5.200345] [8]
[5.466936] [5]
[5.246513] [6]
[5.094563] [8]
[5.5441155] [4]
[5.1543465] [3]
[5.317068] [1]
[5.375884] [2]
[5.025778] [7]
[5.3072844] [1]
[5.076768] [2]
[5.4854927] [3]
[5.3475065] [6]
[5.061894] [9]
[5.5543504] [2]
[5.5816875] [4]
[5.179975] [3]
[5.39062] [4]
[5.0227075] [5]
[5.2666836] [2]
[5.0941157] [6]
[5.448075] [3]
[5.2988434] [4]
[5.0584173] [8]
[5.471015] [7]
[5.0289526] [6]
[5.100638] [0]
[5.4048543] [12]
[5.0156293] [3]
[5.2481365] [6]
[5.1087394] [2]
[5.1265326] [2]
[5.431413] [1]
[5.440328] [3]
[5.013053] [2]
[5.4507017] [2]
[5.527137] [1]
[5.1316285] [7]
[5.1013765] [1]
[5.

In [ ]:
y_test_h

In [ ]:
def one_hot_encoding(run):
       one_hot_vector = [0]*10
       index=run-1
       one_hot_vector[index]=1
       return one_hot_vector

In [ ]:
for i in enumerate(y_test_h):
  a= 