<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/Model8_%EC%83%88%EB%A1%9C%EC%9A%B4_%EB%AA%A8%EB%8D%B8_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%B2%98%EB%A6%AC_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
import pandas as pd
import numpy as np

In [122]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
r_team_hitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/2차_최종_최근_팀타자.csv', encoding='utf-8-sig')
r_team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/2차_최종_최근_팀투수.csv', encoding='utf-8-sig')
vs_r_team_hitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/2차_최종_최근_상대_팀타자.csv', encoding='utf-8-sig')
vs_r_team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/2차_최종_최근_상대_팀투수.csv', encoding='utf-8-sig')
team_data = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_공통.csv', encoding='utf-8-sig')
sr_team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/선발_팀투수_최종.csv', encoding='utf-8-sig')

In [ ]:
sr_team_pitcher

게임키          일자 팀코드  ... 상대_선발_최근 OSLG  선발_최근 OOPS 상대_선발_최근 OOPS
0     20160401HHLG0  2016-04-01  LG  ...      0.000000    0.000000      0.000000
1     20160401HHLG0  2016-04-01  HH  ...      0.000000    0.000000      0.000000
2     20160401HTNC0  2016-04-01  NC  ...      0.000000    0.000000      0.000000
3     20160401HTNC0  2016-04-01  HT  ...      0.000000    0.000000      0.000000
4     20160401KTSK0  2016-04-01  SK  ...      0.000000    0.000000      0.000000
...             ...         ...  ..  ...           ...         ...           ...
6395  20200719LTSS0  2020-07-19  LT  ...      0.388889    0.858230      0.759857
6396  20200719OBHT0  2020-07-19  HT  ...      0.328125    0.830130      0.642411
6397  20200719OBHT0  2020-07-19  OB  ...      0.470588    0.740435      0.835453
6398  20200719WOSK0  2020-07-19  SK  ...      0.517857    0.875875      0.948626
6399  20200719WOSK0  2020-07-19  WO  ...      0.271186    0.741111      0.517340

[6400 rows x 47 columns]

In [ ]:
r_team_hitter

게임키          일자 팀코드 상대팀코드  ...  최근타자득점 최근득점권타수  최근득점권안타   최근득점권타율
0     20160401HHLG0  2016-04-01  LG    HH  ...     0.0     0.0      0.0  0.000000
1     20160401HHLG0  2016-04-01  HH    LG  ...     0.0     0.0      0.0  0.000000
2     20160401HTNC0  2016-04-01  NC    HT  ...     0.0     0.0      0.0  0.000000
3     20160401HTNC0  2016-04-01  HT    NC  ...     0.0     0.0      0.0  0.000000
4     20160401KTSK0  2016-04-01  SK    KT  ...     0.0     0.0      0.0  0.000000
...             ...         ...  ..   ...  ...     ...     ...      ...       ...
6326  20200719LTSS0  2020-07-19  LT    SS  ...     7.0     9.4      3.2  0.340426
6327  20200719OBHT0  2020-07-19  HT    OB  ...     3.2     8.2      1.4  0.170732
6328  20200719OBHT0  2020-07-19  OB    HT  ...     5.2    11.0      3.8  0.345455
6329  20200719WOSK0  2020-07-19  SK    WO  ...     5.8     9.2      3.2  0.347826
6330  20200719WOSK0  2020-07-19  WO    SK  ...     5.2     9.2      2.2  0.239130

[6331 rows x 67 columns]

In [ ]:
r_team_hitter = r_team_hitter[['게임키',  '팀코드', '최근OBP',
       '최근SLG', '최근OPS', '최근GPA', '최근타율', '최근ISO', '최근BABIP', '최근HR%', '최근K%',
       '최근BB%', '최근BBK', '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR',
       '최근SPD', '최근SECA', '최근PSN', '최근PA', '최근B3B', '최근BB', '최근HR', '최근K',
       '최근HBP', '최근IBB', '최근SB', '최근CS', '최근AB', '최근HIT', '최근B1B', '최근B2B',
       '최근타자득점', '최근득점권타수', '최근득점권안타', '최근득점권타율']]

In [ ]:
sr_team_pitcher.columns = ['게임키', '일자', '상대팀코드', '팀코드', '더블헤더코드', '초말', '완투', '결과', '홀드', '이닝*3',
       '투구수', '타자', '타수', '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비',
       '4구', '고4', '사구', '삼진', '병살타', '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP',
       '2점차이하WHIP', '345번타자WHIP', '시즌', '선발_최근 평균자책점', '상대_선발_최근 평균자책점',
       '선발_최근 whip', '상대_선발_최근 whip', '선발_최근 OAVG', '상대_선발_최근 OAVG',
       '선발_최근 OOBP', '상대_선발_최근 OOBP', '선발_최근 OSLG', '상대_선발_최근 OSLG',
       '선발_최근 OOPS', '상대_선발_최근 OOPS']
sr_team_pitcher = sr_team_pitcher[['게임키', '팀코드','선발_최근 평균자책점',
       '선발_최근 whip', '선발_최근 OAVG', 
       '선발_최근 OOBP', '선발_최근 OSLG', 
       '선발_최근 OOPS']]

In [ ]:
vs_r_team_hitter = vs_r_team_hitter[['게임키', '일자', '팀코드', '상대팀코드', '더블헤더코드', '초말', '타자', '타수', '타점', '득점',
       '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비', '4구', '고4', '사구',
       '삼진', '병살타', '실책', '잔루', '득점권타율', '득점권타수', '득점권안타', '시즌', '단타']]

In [ ]:
vs_r_team_pitcher.columns = ['게임키', '일자', '상대팀코드', '팀코드', '더블헤더코드', '초말', '완투', '결과', '홀드', '이닝*3',
       '투구수', '타자', '타수', '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비',
       '4구', '고4', '사구', '삼진', '병살타', '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP',
       '2점차이하WHIP', '345번타자WHIP', '시즌', '상대최근평균자책점', '상대최근RA/9', '상대최근ERC',
       '상대최근FIP', '상대최근LOB', '상대최근홈런율', '상대최근삼진율', '상대최근K9', '상대최근BB9',
       '상대최근HR9', '상대최근KBB', '상대최근whip', '상대최근PFR', '상대최근P/G', '상대최근P/IP',
       '상대최근P/PA', '상대최근CYP', '상대최근kwERA', '상대최근K%', '상대최근BB%', '상대최근OAVG',
       '상대최근OOBP', '단타', '상대최근OSLG', '상대최근OOPS', '상대최근투수AB', '상대최근투수HIT',
       '상대최근투수B1B', '상대최근투수B2B', '상대최근투수B3B', '상대최근투수BB', '상대최근투수HR',
       '상대최근투수K', '상대최근투수HBP', '상대최근투수IBB', '상대최근투수SB', '상대최근투수CS',
       '상대최근투수INN', '상대최근득점권WHIP', '상대최근2점차이하WHIP', '상대최근345번타자WHIP',
       '상대최근투수실점']

In [ ]:
vs_r_team_pitcher = vs_r_team_pitcher[ ['게임키',  '팀코드', '완투', '결과', '홀드', '이닝*3',
       '투구수', '타자', '타수', '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비',
       '4구', '고4', '사구', '삼진', '병살타', '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP',
       '2점차이하WHIP', '345번타자WHIP']]

In [ ]:
r_team = pd.merge(vs_r_team_hitter, vs_r_team_pitcher, on=['게임키', '팀코드'])

In [ ]:
r_team = pd.merge(r_team, r_team_hitter, on=['게임키', '팀코드'])
r_team = pd.merge(r_team, sr_team_pitcher, on=['게임키', '팀코드'])

In [ ]:
r_team

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG 선발_최근 OOPS
0     20160401HHLG0  2016-04-01  LG  ...   0.000000    0.000000   0.000000
1     20160401HHLG0  2016-04-01  HH  ...   0.000000    0.000000   0.000000
2     20160401HTNC0  2016-04-01  NC  ...   0.000000    0.000000   0.000000
3     20160401HTNC0  2016-04-01  HT  ...   0.000000    0.000000   0.000000
4     20160401KTSK0  2016-04-01  SK  ...   0.000000    0.000000   0.000000
...             ...         ...  ..  ...        ...         ...        ...
6326  20200719LTSS0  2020-07-19  LT  ...   0.323232    0.300000   0.623232
6327  20200719OBHT0  2020-07-19  HT  ...   0.360000    0.380435   0.740435
6328  20200719OBHT0  2020-07-19  OB  ...   0.366972    0.463158   0.830130
6329  20200719WOSK0  2020-07-19  SK  ...   0.330000    0.411111   0.741111
6330  20200719WOSK0  2020-07-19  WO  ...   0.366071    0.509804   0.875875

[6331 rows x 101 columns]

In [ ]:
r_team = r_team[r_team['실점'] <= 15]

In [ ]:
a = r_team.groupby('게임키').count().copy()
a[a['일자'] == 1].index

Index(['20160412NCSS0', '20160414OBHH0', '20160415LGHH0', '20160423HTLT0',
       '20160504OBLG0', '20160505HHSK0', '20160505LTHT0', '20160507HHKT0',
       '20160508LTOB0', '20160511SSLG0', '20160511WOLT0', '20160520OBLT0',
       '20160522KTHH0', '20160529LGOB0', '20160609WONC0', '20160622LTHT0',
       '20160719KTHH0', '20160810SSHH0', '20160824LGOB0', '20160901HTSS0',
       '20170402HTSS0', '20170411HTOB0', '20170427SSHT0', '20170504OBSS0',
       '20170525SKLT0', '20170526SSWO0', '20170608LTNC0', '20170611SKLG0',
       '20170618LGHT0', '20170621OBHT0', '20170629SSHT0', '20170708HTKT0',
       '20170722HHOB0', '20170910WOSK0', '20170916KTHT0', '20170917OBSS0',
       '20171001HTKT0', '20180327SSHT0', '20180331OBKT0', '20180403LTHH0',
       '20180520NCKT0', '20180622OBSS0', '20180623LTLG0', '20180711WOHH0',
       '20180721OBLG0', '20180727HHOB0', '20180805WOKT0', '20180809WOHH0',
       '20180811HTSK0', '20180812HTSK0', '20180911OBLT0', '20180918HTSS0',
       '20180919SKKT0', '

In [ ]:
out_list = ['20160412NCSS0', '20160414OBHH0', '20160415LGHH0', '20160423HTLT0',
       '20160504OBLG0', '20160505HHSK0', '20160505LTHT0', '20160507HHKT0',
       '20160508LTOB0', '20160511SSLG0', '20160511WOLT0', '20160520OBLT0',
       '20160522KTHH0', '20160529LGOB0', '20160609WONC0', '20160622LTHT0',
       '20160719KTHH0', '20160810SSHH0', '20160824LGOB0', '20160901HTSS0',
       '20170402HTSS0', '20170411HTOB0', '20170427SSHT0', '20170504OBSS0',
       '20170525SKLT0', '20170526SSWO0', '20170608LTNC0', '20170611SKLG0',
       '20170618LGHT0', '20170621OBHT0', '20170629SSHT0', '20170708HTKT0',
       '20170722HHOB0', '20170910WOSK0', '20170916KTHT0', '20170917OBSS0',
       '20171001HTKT0', '20180327SSHT0', '20180331OBKT0', '20180403LTHH0',
       '20180520NCKT0', '20180622OBSS0', '20180623LTLG0', '20180711WOHH0',
       '20180721OBLG0', '20180727HHOB0', '20180805WOKT0', '20180809WOHH0',
       '20180811HTSK0', '20180812HTSK0', '20180911OBLT0', '20180918HTSS0',
       '20180919SKKT0', '20180925LGSK0', '20181003HTSS0', '20190327SSLT0',
       '20190407HHLT0', '20190421SSHH0', '20190508HHSK0', '20190526KTHT0',
       '20190806LGHT0', '20190807WOLT0', '20190825WOSS0', '20200531NCSS0',
       '20200613WONC0', '20200619OBLG0', '20200625NCKT2']
for i in out_list:
  r_team = r_team[r_team['게임키'] != i]

In [ ]:
r_team

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG 선발_최근 OOPS
0     20160401HHLG0  2016-04-01  LG  ...   0.000000    0.000000   0.000000
1     20160401HHLG0  2016-04-01  HH  ...   0.000000    0.000000   0.000000
2     20160401HTNC0  2016-04-01  NC  ...   0.000000    0.000000   0.000000
3     20160401HTNC0  2016-04-01  HT  ...   0.000000    0.000000   0.000000
4     20160401KTSK0  2016-04-01  SK  ...   0.000000    0.000000   0.000000
...             ...         ...  ..  ...        ...         ...        ...
6326  20200719LTSS0  2020-07-19  LT  ...   0.323232    0.300000   0.623232
6327  20200719OBHT0  2020-07-19  HT  ...   0.360000    0.380435   0.740435
6328  20200719OBHT0  2020-07-19  OB  ...   0.366972    0.463158   0.830130
6329  20200719WOSK0  2020-07-19  SK  ...   0.330000    0.411111   0.741111
6330  20200719WOSK0  2020-07-19  WO  ...   0.366071    0.509804   0.875875

[6264 rows x 101 columns]

In [ ]:
r_team_nc = r_team[r_team['팀코드'] == 'NC']

In [ ]:
r_team_nc = r_team_nc.reset_index()
del r_team_nc['index']
r_team_nc

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG 선발_최근 OOPS
0    20160401HTNC0  2016-04-01  NC  ...   0.000000    0.000000   0.000000
1    20160402HTNC0  2016-04-02  NC  ...   0.384615    0.636364   1.020979
2    20160405NCOB0  2016-04-05  NC  ...   0.408163    0.489362   0.897525
3    20160406NCOB0  2016-04-06  NC  ...   0.394737    0.397059   0.791796
4    20160407NCOB0  2016-04-07  NC  ...   0.323529    0.311828   0.635357
..             ...         ...  ..  ...        ...         ...        ...
627  20200715NCWO0  2020-07-15  NC  ...   0.401869    0.620000   1.021869
628  20200716NCWO0  2020-07-16  NC  ...   0.420561    0.673469   1.094030
629  20200717KTNC0  2020-07-17  NC  ...   0.323077    0.327731   0.650808
630  20200718KTNC0  2020-07-18  NC  ...   0.314961    0.313559   0.628520
631  20200719KTNC0  2020-07-19  NC  ...   0.336134    0.369369   0.705504

[632 rows x 101 columns]

In [ ]:
r_team_nc.head()
index_list = []
for i in range(len(r_team_nc)):
  idx = i
  sum = 0
  vs_team = r_team_nc.iloc[idx]['상대팀코드']
  while idx+1 < len(r_team_nc) and vs_team == r_team_nc.iloc[idx+1]['상대팀코드'] :
    sum += 1
    idx += 1
  if sum == 2:
    index_list.append(i)

In [ ]:
data = r_team_nc.iloc[2: 2+3]
for i in index_list:
  if i == 2:
    continue
  data= pd.concat([data, r_team_nc.iloc[i: i+3]])
data

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG 선발_최근 OOPS
2    20160405NCOB0  2016-04-05  NC  ...   0.408163    0.489362   0.897525
3    20160406NCOB0  2016-04-06  NC  ...   0.394737    0.397059   0.791796
4    20160407NCOB0  2016-04-07  NC  ...   0.323529    0.311828   0.635357
5    20160408HHNC0  2016-04-08  NC  ...   0.452381    0.573529   1.025910
6    20160409HHNC0  2016-04-09  NC  ...   0.454545    0.550725   1.005270
..             ...         ...  ..  ...        ...         ...        ...
627  20200715NCWO0  2020-07-15  NC  ...   0.401869    0.620000   1.021869
628  20200716NCWO0  2020-07-16  NC  ...   0.420561    0.673469   1.094030
629  20200717KTNC0  2020-07-17  NC  ...   0.323077    0.327731   0.650808
630  20200718KTNC0  2020-07-18  NC  ...   0.314961    0.313559   0.628520
631  20200719KTNC0  2020-07-19  NC  ...   0.336134    0.369369   0.705504

[384 rows x 101 columns]

In [ ]:
keys = list(data['게임키'])

In [ ]:
r_team_a = r_team[r_team['게임키'] == keys[0]]
for idx, key in enumerate(keys):
  if idx == 0:
    continue
  r_team_a = pd.concat([r_team_a, r_team[r_team['게임키'] == key]])

In [ ]:
r_team_a = r_team_a[r_team_a['팀코드'] != 'NC']

In [ ]:
data

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG 선발_최근 OOPS
2    20160405NCOB0  2016-04-05  NC  ...   0.408163    0.489362   0.897525
3    20160406NCOB0  2016-04-06  NC  ...   0.394737    0.397059   0.791796
4    20160407NCOB0  2016-04-07  NC  ...   0.323529    0.311828   0.635357
5    20160408HHNC0  2016-04-08  NC  ...   0.452381    0.573529   1.025910
6    20160409HHNC0  2016-04-09  NC  ...   0.454545    0.550725   1.005270
..             ...         ...  ..  ...        ...         ...        ...
627  20200715NCWO0  2020-07-15  NC  ...   0.401869    0.620000   1.021869
628  20200716NCWO0  2020-07-16  NC  ...   0.420561    0.673469   1.094030
629  20200717KTNC0  2020-07-17  NC  ...   0.323077    0.327731   0.650808
630  20200718KTNC0  2020-07-18  NC  ...   0.314961    0.313559   0.628520
631  20200719KTNC0  2020-07-19  NC  ...   0.336134    0.369369   0.705504

[384 rows x 101 columns]

In [ ]:
r_team_a

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG 선발_최근 OOPS
26    20160405NCOB0  2016-04-05  OB  ...   0.380000    0.466667   0.846667
34    20160406NCOB0  2016-04-06  OB  ...   0.430769    0.490909   0.921678
44    20160407NCOB0  2016-04-07  OB  ...   0.386364    0.447368   0.833732
53    20160408HHNC0  2016-04-08  HH  ...   0.382609    0.410000   0.792609
63    20160409HHNC0  2016-04-09  HH  ...   0.372881    0.370000   0.742881
...             ...         ...  ..  ...        ...         ...        ...
6287  20200715NCWO0  2020-07-15  WO  ...   0.371681    0.484211   0.855892
6297  20200716NCWO0  2020-07-16  WO  ...   0.410714    0.478261   0.888975
6304  20200717KTNC0  2020-07-17  KT  ...   0.387931    0.434343   0.822274
6314  20200718KTNC0  2020-07-18  KT  ...   0.381356    0.446602   0.827958
6324  20200719KTNC0  2020-07-19  KT  ...   0.314961    0.333333   0.648294

[384 rows x 101 columns]

In [ ]:
data.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/nc_교차_nc.csv', encoding='utf-8-sig', index=False)
r_team_a.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/nc_교차_상대.csv', encoding='utf-8-sig', index=False)

In [146]:
r_team_nc = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/nc_교차_nc.csv', encoding='utf-8-sig')
r_team_a = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/nc_교차_상대.csv', encoding='utf-8-sig')

In [147]:
def homeaway(row):
  if row['초말'] == 'B':
    row['초말'] = 1
  else:
    row['초말'] = 0
  return row

def winloss(row):
  if row['결과'] == 'W':
    row['결과'] = 1
  else:
    row['결과'] = 0
  return row

r_team_nc = r_team_nc.apply(homeaway, axis=1)
r_team_a = r_team_a.apply(homeaway, axis=1)
r_team_nc = r_team_nc.apply(winloss, axis=1)
r_team_a = r_team_a.apply(winloss, axis=1)

In [153]:
r_team_nc.columns

Index(['게임키', '일자', '팀코드', '상대팀코드', '더블헤더코드', '초말', '타자_x', '타수_x', '타점', '득점',
       ...
       '최근타자득점', '최근득점권타수', '최근득점권안타', '최근득점권타율', '선발_최근 평균자책점', '선발_최근 whip',
       '선발_최근 OAVG', '선발_최근 OOBP', '선발_최근 OSLG', '선발_최근 OOPS'],
      dtype='object', length=101)

In [321]:
encoder_inputs = []
decoder_inputs = []
for idx in range(0, len(r_team_nc), 3):
  row = r_team_nc.iloc[idx]
  previous = r_team_nc[(r_team_nc['일자'] < row['일자']) & (r_team_nc['상대팀코드'] == row['상대팀코드']) & (r_team_nc['시즌'] == row['시즌'])].tail(3)
  if len(previous) == 0:
    continue
  if len(encoder_inputs) == 0:
    encoder_inputs = previous
    decoder_inputs = r_team_nc.iloc[idx: idx+3]
  else:
    encoder_inputs = pd.concat([encoder_inputs, previous])
    decoder_inputs = pd.concat([decoder_inputs, r_team_nc.iloc[idx: idx+3]])

In [322]:
encoder_inputs = encoder_inputs[['초말', '타수_x',  '득점', '안타_x',
       '홈런_x','4구_x',
       '결과', 
       '자책점']]

In [323]:
decoder_outputs = decoder_inputs[['타수_x',  '득점', '안타_x',
       '홈런_x','4구_x',
       '자책점']]

In [224]:
decoder_outputs

초말  타수_x  득점  안타_x  홈런_x  4구_x  자책점
15    1    37  13    15     2     2   13
16    1    32   4     8     3     3    4
17    1    30  11    12     0    10   11
30    1    34   5     8     1     7    5
31    1    33   5     6     0     4    2
..   ..   ...  ..   ...   ...   ...  ...
379   0    34   4    11     1     2    4
380   0    40   9    14     1     4    9
381   1    41   3     8     0     5    3
382   1    33   6    11     1     7    6
383   1    36   8    12     1     4    8

[252 rows x 7 columns]

In [176]:
del decoder_inputs['더블헤더코드']
decoder_inputs.columns

Index(['게임키', '일자', '팀코드', '상대팀코드', '초말', '타자_x', '타수_x', '타점', '득점', '안타_x',
       '2루타_x', '3루타_x', '홈런_x', '도루_x', '도루실패_x', '희타_x', '희비_x', '4구_x',
       '고4_x', '사구_x', '삼진_x', '병살타_x', '실책_x', '잔루', '득점권타율', '득점권타수',
       '득점권안타', '시즌', '단타', '완투', '결과', '홀드', '이닝*3', '투구수', '타자_y', '타수_y',
       '안타_y', '2루타_y', '3루타_y', '홈런_y', '도루_y', '도루실패_y', '희타_y', '희비_y',
       '4구_y', '고4_y', '사구_y', '삼진_y', '병살타_y', '폭투', '보크', '실책_y', '실점',
       '자책점', '득점권WHIP', '2점차이하WHIP', '345번타자WHIP', '최근OBP', '최근SLG', '최근OPS',
       '최근GPA', '최근타율', '최근ISO', '최근BABIP', '최근HR%', '최근K%', '최근BB%', '최근BBK',
       '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근SPD',
       '최근SECA', '최근PSN', '최근PA', '최근B3B', '최근BB', '최근HR', '최근K', '최근HBP',
       '최근IBB', '최근SB', '최근CS', '최근AB', '최근HIT', '최근B1B', '최근B2B', '최근타자득점',
       '최근득점권타수', '최근득점권안타', '최근득점권타율', '선발_최근 평균자책점', '선발_최근 whip',
       '선발_최근 OAVG', '선발_최근 OOBP', '선발_최근 OSLG', '선발_최근 OOPS'],
      dtype='object')

In [324]:
decoder_inputs = decoder_inputs.reset_index()
del decoder_inputs['index']
decoder_inputs

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG  선발_최근 OOPS
0    20160506LGNC0  2016-05-06  NC  ...   0.411215    0.442105    0.853320
1    20160507LGNC0  2016-05-07  NC  ...   0.462264    0.515464    0.977728
2    20160508LGNC0  2016-05-08  NC  ...   0.475248    0.630435    1.105682
3    20160531OBNC0  2016-05-31  NC  ...   0.370079    0.362832    0.732911
4    20160601OBNC0  2016-06-01  NC  ...   0.343750    0.362069    0.705819
..             ...         ...  ..  ...        ...         ...         ...
247  20200715NCWO0  2020-07-15  NC  ...   0.401869    0.620000    1.021869
248  20200716NCWO0  2020-07-16  NC  ...   0.420561    0.673469    1.094030
249  20200717KTNC0  2020-07-17  NC  ...   0.323077    0.327731    0.650808
250  20200718KTNC0  2020-07-18  NC  ...   0.314961    0.313559    0.628520
251  20200719KTNC0  2020-07-19  NC  ...   0.336134    0.369369    0.705504

[252 rows x 101 columns]

In [259]:
decoder_inputs.tail(18)

게임키          일자 팀코드  ... 선발_최근 OOBP  선발_최근 OSLG  선발_최근 OOPS
234  20200609OBNC0  2020-06-09  NC  ...   0.314961    0.413793    0.728754
235  20200610OBNC0  2020-06-10  NC  ...   0.327731    0.368932    0.696663
236  20200611OBNC0  2020-06-11  NC  ...   0.303279    0.385321    0.688600
237  20200619HHNC0  2020-06-19  NC  ...   0.423423    0.489796    0.913219
238  20200620HHNC0  2020-06-20  NC  ...   0.404959    0.477064    0.882023
239  20200621HHNC0  2020-06-21  NC  ...   0.398305    0.467290    0.865595
240  20200626NCOB0  2020-06-26  NC  ...   0.338843    0.418803    0.757646
241  20200627NCOB0  2020-06-27  NC  ...   0.358333    0.438596    0.796930
242  20200628NCOB0  2020-06-28  NC  ...   0.361345    0.482143    0.843487
243  20200707NCSK0  2020-07-07  NC  ...   0.421488    0.378641    0.800128
244  20200708NCSK0  2020-07-08  NC  ...   0.390244    0.370370    0.760614
245  20200709NCSK0  2020-07-09  NC  ...   0.330579    0.311927    0.642505
246  20200714NCWO0  2020-07-14  NC  ...   0.434343    0.633333    1.067677
247  20200715NCWO0  2020-07-15  NC  ...   0.401869    0.620000    1.021869
248  20200716NCWO0  2020-07-16  NC  ...   0.420561    0.673469    1.094030
249  20200717KTNC0  2020-07-17  NC  ...   0.323077    0.327731    0.650808
250  20200718KTNC0  2020-07-18  NC  ...   0.314961    0.313559    0.628520
251  20200719KTNC0  2020-07-19  NC  ...   0.336134    0.369369    0.705504

[18 rows x 101 columns]

In [325]:
decoder_inputs_values = []
for idx in range(len(decoder_inputs)):
  if idx % 3 == 0:
    data = list(decoder_inputs.iloc[idx][['초말','최근AB','최근HIT','최근타자득점','최근HR','최근BB', '선발_최근 평균자책점']].values)
    decoder_inputs_values.append(data)
  else:
    data = list(decoder_inputs.iloc[idx -1][['초말', '타수_x',  '득점', '안타_x', '홈런_x','4구_x', '자책점']].values)
    decoder_inputs_values.append(data)

In [228]:
np.array(decoder_inputs_values)

array([[ 1.        , 37.2       , 11.8       , ...,  2.        ,
         4.8       ,  5.625     ],
       [ 1.        , 37.        , 13.        , ...,  2.        ,
         2.        , 13.        ],
       [ 1.        , 32.        ,  4.        , ...,  3.        ,
         3.        ,  4.        ],
       ...,
       [ 1.        , 37.6       , 10.4       , ...,  1.2       ,
         2.8       ,  3.19354839],
       [ 1.        , 41.        ,  3.        , ...,  0.        ,
         5.        ,  3.        ],
       [ 1.        , 33.        ,  6.        , ...,  1.        ,
         7.        ,  6.        ]])

In [326]:
encoder_inputs = encoder_inputs.values
decoder_inputs = np.array(decoder_inputs_values)
decoder_outputs = decoder_outputs.values

In [327]:
encoder_input = encoder_inputs.reshape(-1, 3, 8)

In [328]:
encoder_input_train = encoder_input[0: 78]
encoder_input_test = encoder_input[78:]

In [329]:
decoder_input = decoder_inputs.reshape(-1, 3, 7)
decoder_input_train = decoder_input[0: 78]
decoder_input_test = decoder_input[78:]

In [330]:
decoder_output = decoder_outputs.reshape(-1, 3, 6)
decoder_output_train = decoder_output[0: 78]
decoder_output_test = decoder_output[78:]

In [339]:
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense
from tensorflow.keras.models import Model

encoder_inputs = Input(shape=(None, 8))
encoder_lstm = LSTM(units=32, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)

encoder_states = [state_h, state_c]

decoder_inputs = Input(shape=(None, 7))
decoder_lstm = LSTM(units=32, return_sequences=True, return_state=True)
decoder_outputs, _, _= decoder_lstm(decoder_inputs, initial_state=encoder_states)
# 디코더의 첫 상태를 인코더의 은닉 상태, 셀 상태로 합니다.
decoder_full_layer = Dense(6, activation='relu')
decoder_outputs = decoder_full_layer(decoder_outputs)

model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer="adam", loss="mse")

model.fit(x=[encoder_input_train, decoder_input_train], y=decoder_output_train, batch_size=3, epochs=150, validation_split=0.2)


Epoch 1/150
21/21 [==============================] - 1s 38ms/step - loss: 231.1699 - val_loss: 232.8497
Epoch 2/150
21/21 [==============================] - 0s 4ms/step - loss: 228.5911 - val_loss: 230.8206
Epoch 3/150
21/21 [==============================] - 0s 4ms/step - loss: 226.5527 - val_loss: 229.0421
Epoch 4/150
21/21 [==============================] - 0s 5ms/step - loss: 224.7181 - val_loss: 227.8195
Epoch 5/150
21/21 [==============================] - 0s 5ms/step - loss: 223.6923 - val_loss: 227.6137
Epoch 6/150
21/21 [==============================] - 0s 5ms/step - loss: 223.4542 - val_loss: 227.6369
Epoch 7/150
21/21 [==============================] - 0s 5ms/step - loss: 223.4177 - val_loss: 227.6066
Epoch 8/150
21/21 [==============================] - 0s 5ms/step - loss: 221.0088 - val_loss: 222.4139
Epoch 9/150
21/21 [==============================] - 0s 5ms/step - loss: 216.3070 - val_loss: 218.8612
Epoch 10/150
21/21 [==============================] - 0s 5ms/step - loss

In [350]:
encoder_model = Model(inputs=encoder_inputs, outputs=encoder_states)

decoder_state_input_h = Input(shape=(32,))
decoder_state_input_c = Input(shape=(32,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state=decoder_states_inputs)

decoder_states = [state_h, state_c]

decoder_outputs = decoder_full_layer(decoder_outputs)
decoder_model = Model(inputs=[decoder_inputs] + decoder_states_inputs, outputs=[decoder_outputs] + decoder_states)

In [351]:
states_value = encoder_model.predict(encoder_input_test[0].reshape(-1,3,8))


In [359]:
np.append([1], decoder_input_test[0, 0])

array([ 1.        ,  1.        , 38.4       , 13.6       , 10.6       ,
        2.6       ,  5.8       ,  4.34482759])

In [361]:
test = decoder_input_test[0, 0].reshape(-1, 1, 7)
for i in range(3):
  output_tokens, h, c = decoder_model.predict([test] + states_value)
  print(output_tokens)
  test = np.append([1], output_tokens[0, 0, :]).reshape(-1, 1, 7)
  states_value = [h, c]

[[[34.65108    5.4962773  9.950993   1.03601    3.652172   4.9744234]]]
[[[34.94277    5.48631    9.958861   1.0892454  3.5857506  4.94305  ]]]
[[[34.925163   5.4565654  9.946174   1.0946926  3.550974   4.9055943]]]


In [341]:
output_tokens, h, c = decoder_model.predict([decoder_input_test[0, 0].reshape(-1, 1, 7)] + states_value)

In [342]:
output_tokens

array([[[ 0.49605715, 34.41872   ,  0.        ,  9.667175  ,
          0.        ,  3.6228676 ,  4.666974  ]]], dtype=float32)

In [362]:
decoder_output_test[0]

array([[34, 12, 12,  1,  7, 12],
       [34,  1,  7,  1,  0,  1],
       [37,  7, 14,  1,  0,  7]])

In [364]:
states_value = encoder_model.predict(encoder_input_test[1].reshape(-1,3,8))
test = decoder_input_test[1, 0].reshape(-1, 1, 7)
for i in range(3):
  output_tokens, h, c = decoder_model.predict([test] + states_value)
  print(output_tokens)
  test = np.append([1], output_tokens[0, 0, :]).reshape(-1, 1, 7)
  states_value = [h, c]

[[[34.736004    5.2823253   9.975455    0.86049783  3.6599803
    4.8606763 ]]]
[[[34.95102    5.49029    9.959375   1.0889779  3.5856874  4.9491777]]]
[[[34.90276    5.4464703  9.937886   1.0931878  3.5401225  4.8968086]]]


In [365]:
decoder_output_test[1]

array([[30,  3,  7,  1,  2,  3],
       [34,  3,  8,  1,  0,  2],
       [35,  9, 11,  1,  4,  7]])

In [366]:
states_value = encoder_model.predict(encoder_input_test[2].reshape(-1,3,8))
test = decoder_input_test[2, 0].reshape(-1, 1, 7)
for i in range(3):
  output_tokens, h, c = decoder_model.predict([test] + states_value)
  print(output_tokens)
  test = np.append([1], output_tokens[0, 0, :]).reshape(-1, 1, 7)
  states_value = [h, c]

[[[34.668526    5.2527127   9.93525     0.86619556  3.655433
    4.8394227 ]]]
[[[34.774845   5.404669   9.88832    1.0905164  3.540573   4.86916  ]]]
[[[34.165073   5.132373   9.695049   1.1102935  3.3060703  4.562667 ]]]


In [367]:
decoder_output_test[2]

array([[32,  9, 11,  0,  4,  8],
       [33,  3,  6,  2,  1,  3],
       [38,  5, 12,  3,  2,  5]])