<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/Model5_%EB%93%9D%EC%A0%90_%EC%8B%A4%EC%A0%90_basic_%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [3]:
data = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/팀별 raw 데이터.csv', encoding='utf-8-sig')

In [4]:
data['일자'] = pd.to_datetime(data['일자'], format='%Y-%m-%d', errors='raise')
data['시즌'] = data['일자'].dt.year

In [5]:
team_list = []
for year in range(2016, 2021):
  a = data[(data['일자'] > '{}-05-10'.format(year)) & (data['시즌'] == year)]
  team_list.append(a)
data = pd.concat(team_list)

In [6]:
data = data[data['결과'] != 'D']
data = data[(data['우취'] != 1 ) & (data['연장'] != 1)]
out_list = ['20160810LTNC0', '20170712NCHT0', '20170725SKHT0', '20190529SSOB0', '20200512KTNC0', '20200521SKWO0', '20200703LGSS0']
for i in out_list:
  data = data[data['게임키'] != i]

In [15]:
data = data[data['득점'] <=10]

In [16]:
data = data[data['실점'] <=10]

In [10]:
data['득점'].describe()['mean']

5.31064958020327

In [57]:
x_data = data[[
        'SLG', 'OPS', '타율',
       'BABIP', 'ISO', 'HR%_x', 'K%_x',  'BBK', 'wOBA',  'wRC',
       'RC', 'RC27', 'XR', 'SPD', 'SECA','RBI_PCT', 
       'RA/9', 'ERC', 'FIP','LOB', 'HR%_y', 'K9',
       'BB9', 'KBB', 'whip', 'P/G', 'P/IP', 'P/PA', 'PFR', 'CYP', 
      'OOPS',  '상대RA/9', '상대ERC',
       '상대kwERA', '상대LOB', '상대HR%_x',  '상대BB9', '상대HR9', 
       '상대whip','상대P/G', '상대P/IP','상대P/PA', '상대CYP', 
        '상대OAVG', '상대OSLG', '상대HR%_y', 
       '상대BB%_y', '상대wOBA', '상대wRAA', '상대wRC', '상대RC27',
       '상대SPD',  '상대PSN', '최근OBP',  '최근GPA',
       '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK',
       '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근SPD',
       '최근PSN', '최근평균자책점',  '최근FIP', 
       '최근LOB', '최근HR%_y', '최근K%_y', '최근BB%_y', '최근HR9',
      '최근P/G', '최근P/IP','최근CYP',
      '최근R-E',  '선발_평균자책점',
        '선발_whip',
      '선발_FIP',  '선발_LOB', '선발_홈런율', '선발_삼진율',
       '선발_K%', 
       '선발_OAVG',  '선발_OOBP']]
y_data = data[['득점']]


In [148]:
# 'SLG', 'OPS', '타율',
#        'BABIP', 'ISO', 'HR%_x', 'K%_x',  'BBK', 'wOBA',  'wRC',
#        'RC', 'RC27', 'XR', 'SPD', 'SECA','RBI_PCT',
# '상대HR%_y', 
#        '상대BB%_y', '상대wOBA', '상대wRAA', '상대wRC', '상대RC27',
#        '상대SPD',  '상대PSN', '최근OBP',  '최근GPA',
#        '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK',
#        '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근SPD',
#        '최근PSN' 

x_data = data[[ '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK','상대평균득점',
       '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근평균득점',
       'RA/9', 'ERC', 'FIP','LOB', 'HR%_y', 'K9',
       'BB9', 'KBB', 'whip', 'P/G', 'P/IP', 'P/PA', 'PFR', 'CYP', 
      'OOPS',  '상대RA/9', '상대ERC',
       '상대kwERA', '상대LOB', '상대HR%_x',  '상대BB9', '상대HR9', 
       '상대whip','상대P/G', '상대P/IP','상대P/PA', '상대CYP', 
        '상대OAVG', '상대OSLG', '최근평균자책점',  '최근FIP', 
       '최근LOB', '최근HR%_y', '최근K%_y', '최근BB%_y', '최근HR9',
      '최근P/G', '최근P/IP','최근CYP',
      '최근R-E','선발_평균자책점',
        '선발_whip',
      '선발_FIP',  '선발_LOB', '선발_홈런율', '선발_삼진율',
       '선발_K%', 
       '선발_OAVG',  '선발_OOBP'
       ]]

x_data_h = data[[
       '최근타율', '최근BABIP', '최근ISO', '최근K%_x', '최근BB%_x', '최근BBK','상대평균득점',
       '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR', '최근평균득점'
       ]]
       
x_data_p = data[['RA/9', 'ERC', 'FIP','LOB', 'HR%_y', 'K9',
       'BB9', 'KBB', 'whip', 'P/G', 'P/IP', 'P/PA', 'PFR', 'CYP', 
      'OOPS',  '상대RA/9', '상대ERC',
       '상대kwERA', '상대LOB', '상대HR%_x',  '상대BB9', '상대HR9', 
       '상대whip','상대P/G', '상대P/IP','상대P/PA', '상대CYP', 
        '상대OAVG', '상대OSLG', '최근평균자책점',  '최근FIP', 
       '최근LOB', '최근HR%_y', '최근K%_y', '최근BB%_y', '최근HR9',
      '최근P/G', '최근P/IP','최근CYP',
      '최근R-E','선발_평균자책점',
        '선발_whip',
      '선발_FIP',  '선발_LOB', '선발_홈런율', '선발_삼진율',
       '선발_K%', 
       '선발_OAVG',  '선발_OOBP']]

y_data_h = data[['득점']]
y_data_p = data[['실점']]

In [102]:
y_data_p = data[['결과']]

In [120]:
columns = ['RA/9', 'ERC', 'FIP','LOB', 'HR%_y', 'K9',
        'BB9', 'KBB', 'whip', 'P/G', 'P/IP', 'P/PA', 'PFR', 'CYP', 
        'OOPS',  '상대RA/9', '상대ERC',
        '상대kwERA', '상대LOB', '상대HR%_x',  '상대BB9', '상대HR9', 
        '상대whip','상대P/G', '상대P/IP','상대P/PA', '상대CYP', 
          '상대OAVG', '상대OSLG', '최근평균자책점',  '최근FIP', 
        '최근LOB', '최근HR%_y', '최근K%_y', '최근BB%_y', '최근HR9',
        '최근P/G', '최근P/IP','최근CYP',
        '최근R-E','선발_평균자책점',
          '선발_whip',
        '선발_FIP',  '선발_LOB', '선발_홈런율', '선발_삼진율',
        '선발_K%', 
        '선발_OAVG',  '선발_OOBP']

In [109]:
for i in range(0, len(x_data), 2):
  x_data[columns].iloc[i] = x_data_p.iloc[i+1]
  x_data[columns].iloc[i+1] = x_data_p.iloc[i]
      

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid d

In [151]:
x_data = x_data.reset_index()
del x_data['index']
x_data = x_data.reset_index()
x_data_p = x_data_p.reset_index()
del x_data_p['index']
x_data_p = x_data_p.reset_index()

In [152]:
def mergeAD(row):
  index = int(row['index'])
  print(index)
  if (index % 2) == 0: 
    for col in columns:
      row[col] = x_data_p.iloc[index+1][col]
  else:
    for col in columns:
      row[col] = x_data_p.iloc[index-1][col]
  return row

In [153]:
x_data = x_data.apply(mergeAD, axis=1)

0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276


In [149]:
x_data

최근타율  최근BABIP  최근ISO  최근K%_x  ...    선발_삼진율     선발_K%   선발_OAVG   선발_OOBP
306   0.322    0.366  0.205   0.172  ...  0.155150  0.155150  0.284242  0.352243
307   0.362    0.438  0.102   0.175  ...  0.124438  0.124438  0.291161  0.371385
308   0.263    0.295  0.160   0.185  ...  0.153846  0.153846  0.320896  0.432377
309   0.360    0.389  0.230   0.137  ...  0.176218  0.175714  0.244337  0.320290
310   0.344    0.382  0.198   0.163  ...  0.176755  0.176755  0.246556  0.325581
...     ...      ...    ...     ...  ...       ...       ...       ...       ...
6395  0.320    0.354  0.152   0.146  ...  0.168353  0.168110  0.274168  0.327286
6396  0.272    0.320  0.099   0.167  ...  0.195003  0.195003  0.266513  0.320728
6397  0.325    0.344  0.112   0.089  ...  0.165349  0.165023  0.289474  0.347047
6398  0.278    0.319  0.097   0.183  ...  0.167109  0.166998  0.262718  0.346179
6399  0.280    0.320  0.173   0.186  ...  0.158345  0.158120  0.281911  0.340258

[3698 rows x 63 columns]

In [155]:
del x_data['index']

In [156]:
x_data.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/공수듀얼체인지.csv', encoding='utf-8-sig', index=False)

In [87]:
x_data_h.shape

(3698, 14)

In [88]:
x_data_h = x_data_h.values
x_data_p = x_data_p.values
y_data_h = y_data_h.values
y_data_p = y_data_p.values

In [89]:
x_data_p.shape

(3698, 49)

In [90]:
x_test_h

array([[ 0.60185185,  0.35874439,  0.07936508, ...,  0.73536909,
         0.1589767 ,  0.42553191],
       [-0.89814815, -0.30493274, -0.93650794, ..., -1.00442179,
        -0.43246536, -0.68085106],
       [-0.15740741,  0.16143498, -0.17460317, ..., -0.34958123,
        -1.38267093, -1.10638298],
       ...,
       [ 1.00925926,  0.59192825, -0.14285714, ...,  0.50938979,
         1.04583524,  0.17021277],
       [ 0.13888889,  0.14349776, -0.38095238, ...,  0.23451074,
         0.74554591,  0.42553191],
       [ 0.17592593,  0.16143498,  0.82539683, ...,  0.64755761,
         0.21379625,  0.17021277]])

In [93]:
x_train_h

array([[ 0.299,  0.368,  0.126, ...,  5.316, 28.182,  7.4  ],
       [ 0.292,  0.317,  0.123, ...,  5.585, 28.192,  7.   ],
       [ 0.25 ,  0.286,  0.085, ...,  4.052, 19.198,  4.   ],
       ...,
       [ 0.337,  0.387,  0.168, ...,  7.593, 38.43 ,  9.8  ],
       [ 0.274,  0.287,  0.167, ...,  4.727, 25.362,  4.4  ],
       [ 0.253,  0.307,  0.062, ...,  3.175, 16.028,  2.2  ]])

In [92]:
from sklearn.model_selection import train_test_split
x_train_h, x_test_h, y_train_h, y_test_h = train_test_split(
    x_data_h, y_data_h, test_size = 0.25 
)
from sklearn.model_selection import train_test_split
x_train_p, x_test_p, y_train_p, y_test_p = train_test_split(
    x_data_p, y_data_p, test_size = 0.25 
)

In [94]:
y_test_h

array([[ 2],
       [ 5],
       [10],
       [ 5],
       [ 6],
       [10],
       [ 4],
       [ 7],
       [ 0],
       [ 5],
       [ 8],
       [ 4],
       [ 9],
       [ 1],
       [ 1],
       [ 7],
       [ 7],
       [ 3],
       [ 7],
       [ 8],
       [ 1],
       [ 8],
       [ 4],
       [ 4],
       [ 6],
       [10],
       [ 8],
       [ 2],
       [ 1],
       [ 5],
       [ 2],
       [ 6],
       [ 4],
       [ 6],
       [ 6],
       [ 6],
       [ 4],
       [ 4],
       [ 4],
       [ 3],
       [ 6],
       [ 1],
       [ 5],
       [ 2],
       [ 7],
       [ 6],
       [ 5],
       [ 1],
       [ 5],
       [ 4],
       [ 7],
       [ 8],
       [ 3],
       [ 1],
       [ 8],
       [ 2],
       [ 7],
       [ 1],
       [ 4],
       [ 1],
       [ 4],
       [10],
       [ 4],
       [ 8],
       [ 6],
       [ 3],
       [ 8],
       [ 4],
       [ 2],
       [ 4],
       [ 9],
       [ 8],
       [ 2],
       [ 2],
       [ 8],
       [ 5],
       [ 7],

In [95]:
from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_train_h))
x_train_h = robustScaler.transform(x_train_h)

from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_test_h))
x_test_h = robustScaler.transform(x_test_h)

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)
RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)


In [62]:
y_train_h = y_train_h / 10
y_test_h = y_test_h / 10

In [100]:
#득점
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics, optimizers

model_h = Sequential()
model_h.add(Dense(64, input_shape=(14, ), kernel_initializer='he_normal', activation='relu'))
model_h.add(Dropout(0.5))  
model_h.add(Dense(32, kernel_initializer='he_normal',activation = 'leaky_relu'))
model_h.add(Dropout(0.5))  
model_h.add(Dense(8, kernel_initializer='he_normal',activation = 'relu'))
model_h.add(Dropout(0.5))  
model_h.add(Dense(1,activation = 'relu'))

adam = optimizers.Adam(lr = 0.01) 

model_h.compile(loss='mse', optimizer = 'adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model_h.fit(x_train_h, y_train_h, validation_split=0.2, verbose = 1,
          batch_size=1, epochs=100, callbacks = [early_stopping])

loss, accuracy = model_h.evaluate(x_test_h, y_test_h, batch_size=1)
print('lose: ', loss)
print('mse: ', accuracy)

y_pred = model_h.predict(x_test_h)

ValueError: ignored

In [40]:
x_test_h

array([[ 0.23076923,  1.        ,  0.60655738, ...,  0.1589767 ,
         0.42553191,  0.39478879],
       [-0.61538462, -0.72413793, -0.2295082 , ..., -0.43246536,
        -0.68085106, -0.59218318],
       [ 0.        , -0.55172414,  0.52459016, ..., -1.38267093,
        -1.10638298, -1.18436636],
       ...,
       [-0.46153846, -0.86206897,  0.39344262, ...,  1.04583524,
         0.17021277,  0.07895776],
       [ 0.53846154, -0.27586207, -0.50819672, ...,  0.74554591,
         0.42553191,  1.11843664],
       [ 0.92307692,  1.5862069 ,  0.78688525, ...,  0.21379625,
         0.17021277,  1.92459534]])

In [98]:
for i in range(len(y_pred)):
  print(y_pred[i], y_test_h[i])

[4.375544] [2]
[4.6004796] [5]
[4.305572] [10]
[4.305572] [5]
[4.331344] [6]
[4.732557] [10]
[4.305572] [4]
[4.7788253] [7]
[4.305572] [0]
[4.5629206] [5]
[4.4123864] [8]
[4.305572] [4]
[4.305572] [9]
[4.8021994] [1]
[4.5070987] [1]
[4.5403414] [7]
[4.305572] [7]
[4.734688] [3]
[4.9644704] [7]
[4.521389] [8]
[4.305572] [1]
[4.435012] [8]
[4.719207] [4]
[4.3712645] [4]
[4.305572] [6]
[4.7331686] [10]
[4.689235] [8]
[4.305572] [2]
[4.641973] [1]
[4.305572] [5]
[4.4742227] [2]
[4.3601084] [6]
[4.687461] [4]
[4.5819726] [6]
[4.4544506] [6]
[4.645116] [6]
[4.780308] [4]
[4.305572] [4]
[4.4605565] [4]
[4.537313] [3]
[4.584348] [6]
[4.444161] [1]
[4.305572] [5]
[4.30685] [2]
[4.4946394] [7]
[4.305572] [6]
[4.3788853] [5]
[4.305572] [1]
[4.305572] [5]
[4.502515] [4]
[4.4606686] [7]
[4.305572] [8]
[4.570982] [3]
[4.305572] [1]
[4.305572] [8]
[4.305572] [2]
[5.0528674] [7]
[4.573725] [1]
[4.5450363] [4]
[4.305572] [1]
[4.6046624] [4]
[4.305572] [10]
[4.8714914] [4]
[4.5787234] [8]
[4.4768867] [6

In [54]:
x_test_h[0:3,]

array([[ 0.60185185,  0.35874439,  0.07936508, -1.21465969,  1.31034483,
         2.47325103,  0.4218096 ,  0.69635628,  0.79395604,  1.05256452,
         0.7214503 ,  0.78069031,  0.73536909,  0.1589767 ,  0.42553191,
         0.39478879],
       [-0.89814815, -0.30493274, -0.93650794,  1.2565445 ,  0.06896552,
        -0.5308642 , -0.21573468, -0.92307692, -0.81365333, -0.54787479,
        -0.96333671, -0.89503025, -1.00442179, -0.43246536, -0.68085106,
        -0.59218318],
       [-0.15740741,  0.16143498, -0.17460317,  0.92146597, -0.48275862,
        -0.52263374, -0.21573468, -0.3562753 , -0.27322206, -0.07956068,
        -0.35583164, -0.25121575, -0.34958123, -1.38267093, -1.10638298,
        -1.18436636]])

In [ ]:
model_h.predict(x_test_h[0:10,])

array([[5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548],
       [5.4859548]], dtype=float32)

In [55]:
from sklearn.metrics import mean_squared_error, r2_score, mean_squared_log_error
import numpy as np
def RMSE(y_test, y_pred):
  return np.sqrt(mean_squared_error(y_test, y_pred))
def RMSLE(y_test, y_pred):
  return np.sqrt(mean_squared_log_error(y_test, y_pred))
rsme = RMSE(y_test_h, y_pred)
rsmle = RMSLE(y_test_h, y_pred)
r2 = r2_score(y_test_h, y_pred)

In [ ]:
from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_train_p))
x_train_p = robustScaler.transform(x_train_p)

from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()
print(robustScaler.fit(x_test_p))
x_test_p = robustScaler.transform(x_test_p)

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)
RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)


In [56]:
print(rsme)
print(rsmle)
print(r2)

0.2806744195892578
0.20219734577190607
-0.06075840323720483


In [ ]:
#실점
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics

model_p = Sequential()
model_p.add(Dense(64, input_shape=(49, ), kernel_initializer='he_normal', activation='relu'))
model_p.add(Dropout(0.5))  
model_p.add(Dense(64, kernel_initializer='he_normal',activation = 'relu'))
model_p.add(Dropout(0.5))  
model_p.add(Dense(32, kernel_initializer='he_normal',activation = 'relu'))
model_p.add(Dropout(0.5))  
model_p.add(Dense(1))

model_p.compile(loss='mse', optimizer = 'adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model_p.fit(x_train_p, y_train_p, validation_split=0.2, verbose = 1,
          batch_size=1, epochs=100, callbacks = [early_stopping])

loss, accuracy = model_p.evaluate(x_test_p, y_test_p, batch_size=1)
print('lose: ', loss)
print('mse: ', accuracy)

y_pred_p = model_p.predict(x_test_p)

Epoch 1/100
2070/2070 [==============================] - 4s 2ms/step - loss: 15.4162 - mse: 15.4162 - val_loss: 10.9708 - val_mse: 10.9708
Epoch 2/100
2070/2070 [==============================] - 3s 2ms/step - loss: 10.6565 - mse: 10.6565 - val_loss: 10.1033 - val_mse: 10.1033
Epoch 3/100
2070/2070 [==============================] - 3s 1ms/step - loss: 9.5183 - mse: 9.5183 - val_loss: 8.9569 - val_mse: 8.9569
Epoch 4/100
2070/2070 [==============================] - 3s 1ms/step - loss: 8.9902 - mse: 8.9902 - val_loss: 9.2104 - val_mse: 9.2104
Epoch 5/100
2070/2070 [==============================] - 3s 1ms/step - loss: 8.7607 - mse: 8.7607 - val_loss: 8.5754 - val_mse: 8.5754
Epoch 6/100
2070/2070 [==============================] - 3s 1ms/step - loss: 8.1047 - mse: 8.1047 - val_loss: 7.8538 - val_mse: 7.8538
Epoch 7/100
2070/2070 [==============================] - 3s 1ms/step - loss: 8.1910 - mse: 8.1910 - val_loss: 7.8474 - val_mse: 7.8474
Epoch 8/100
2070/2070 [========================

In [ ]:
for i in range(len(y_pred)):
  print(y_pred[i], y_test_h[i])

[5.1632667] [3]
[5.0301685] [2]
[5.4435763] [3]
[5.048087] [2]
[5.4715705] [6]
[5.115162] [1]
[5.582367] [3]
[5.2090945] [2]
[5.102939] [0]
[5.3908873] [6]
[5.184081] [5]
[5.0652905] [1]
[5.662124] [13]
[5.084039] [3]
[5.5043716] [5]
[5.1710835] [2]
[5.5433774] [0]
[5.2778215] [4]
[5.0962296] [5]
[5.428798] [2]
[5.218754] [1]
[5.1729445] [4]
[5.7428827] [4]
[5.032821] [7]
[5.4902334] [3]
[5.200345] [8]
[5.466936] [5]
[5.246513] [6]
[5.094563] [8]
[5.5441155] [4]
[5.1543465] [3]
[5.317068] [1]
[5.375884] [2]
[5.025778] [7]
[5.3072844] [1]
[5.076768] [2]
[5.4854927] [3]
[5.3475065] [6]
[5.061894] [9]
[5.5543504] [2]
[5.5816875] [4]
[5.179975] [3]
[5.39062] [4]
[5.0227075] [5]
[5.2666836] [2]
[5.0941157] [6]
[5.448075] [3]
[5.2988434] [4]
[5.0584173] [8]
[5.471015] [7]
[5.0289526] [6]
[5.100638] [0]
[5.4048543] [12]
[5.0156293] [3]
[5.2481365] [6]
[5.1087394] [2]
[5.1265326] [2]
[5.431413] [1]
[5.440328] [3]
[5.013053] [2]
[5.4507017] [2]
[5.527137] [1]
[5.1316285] [7]
[5.1013765] [1]
[5.

In [ ]:
y_test_h

In [ ]:
def one_hot_encoding(run):
       one_hot_vector = [0]*10
       index=run-1
       one_hot_vector[index]=1
       return one_hot_vector

In [ ]:
y_pred.shape

(1110, 1)

In [ ]:
wl = []
for i in range(0,len(y_pred_p), 2):
  pt_h = y_pred[i]/y_pred_p[i]/2
  pt_a = y_pred[i+1]/y_pred_p[i+1]/2
  if pt_h >= pt_a:
    wl.append(1)
  else:
    wl.append(0)

In [ ]:
len(wl)

555

In [ ]:
from sklearn.model_selection import train_test_split
x_train_p, x_test_p, y_train_p, y_test_p = train_test_split(
    x_data_p, y_data_p, test_size = 0.3 ,shuffle=False
)

In [ ]:
y_test_p

결과
4958  L
4959  W
4960  W
4961  L
4964  W
...  ..
6395  W
6396  L
6397  W
6398  W
6399  L

[1110 rows x 1 columns]

In [ ]:
pt = y_test_p[0::2]

In [ ]:
def winloss(row):
  if row['결과'] == 'W':
    row['결과'] = 1
  else:
    row['결과'] = 0
  
  return row
pt = pt.apply(winloss, axis=1)
pt

결과
4958   0
4960   1
4964   1
4966   0
4968   0
...   ..
6390   1
6392   1
6394   0
6396   0
6398   1

[555 rows x 1 columns]

In [ ]:
pt = pt.values.reshape(-1)

In [ ]:
wl

[1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [ ]:
good = 0
for i in range(len(wl)):
  if wl[i] == pt[i]:
    good+=1
  

In [ ]:
good / len(wl)

0.5369369369369369